config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  get 'flats/:id', to: 'flats#show', as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  def index
    # render index.html.erb
    @flats = fetch_flats
  end

  def show
   
    flats = fetch_flats

    id = params[:id].to_i

    @flat = flats.find { |flat| flat['id'] == id } 
  end

  private

  def fetch_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    JSON.parse(open(url).read)
  end
end

# RAILS CRUD PATTERNS
# 7 PATHS

# C (2)
# R (2)
  # INDEX - to read many (maybe all)
  # SHOW - to read ONE
# U (2)
# D (1)

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Welcome to my home page</h1>

<% @flats.each do |flat| %>
    <%= link_to flat_path(flat['id']) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= flat['imageUrl'] %>)">
        <%= flat['name'] %>
        | &nbsp
        <small>  <%= flat['price'] %> <%= flat['priceCurrency'] %> </small>
      </div>
    <% end %>
<% end %>

app/views/flats/old_card.html.erb
<%# OLD CARD IS HERE just for teaching purposes %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= flat['imageUrl'] %>)">
  <%# <a href="/flats/<%= flat['id']"><%= flat['name'] </a> %>
  <%# link_to(flat['name'], "/flats/#{flat['id']}")  %>
  <%= link_to(flat['name'], flat_path(flat['id']))  %>
    | &nbsp
  <small>  <%= flat['price'] %> <%= flat['priceCurrency'] %> </small>
</div>

app/views/flats/show.html.erb
<h1>Welcome to <%= @flat['name'] %></h1>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @flat['imageUrl'] %>)">
  Only <%= @flat['price'] %> <%= @flat['priceCurrency'] %> for each night!
</div>

<%= link_to 'Back to home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DblessAirbnb605</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>